linters:
  disable-all: true
  enable-all: false
  enable:
    - deadcode
    - errcheck
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck

linters-settings:
  gofmt:
    simplify: true
